spring:
  application:
    name: comunicacao_api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/comunicacao_api?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8090
  servlet:
    context-path: /comunicacao_api


notificacao:
  url: ${NOTIFICACAO_URL:http://localhost:8082/email}
